project:
  type: website
  output-dir: .

website:
  title: "Yonas Gebre Marie | Data Science Masters Student"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



